src/config.h

Jeb issue #22 closes #22 (suggested issue was #25 but is issue 22 at url: https://github.com/orgs/WSU-CEG-6110-4410/projects/9/views/1)
Key bound in config.h, I will add functionality main.c in future change.

Added keybinding for left alt key to increase user speed

---

src/config.h

#29 
(Relates to 25 in project)

Added key binding for quit button to config.h

---

src/main.c

enabled double jumping...and triple and quadruple jumping…and infinite jumping. This satisfies requirements for user story #2.

Issue #2 Addressed

---

README.md
src/main.c

Added function to check for a sprint key, increase user speed around the map, and documentation of control in ReadMe file. Issue #26 and issue #37

Jeb Closes issue #26 and issue #37

---

src/main.c

#40 and #42
Right now, the block range is 0 to 56.

Issues #40 and #42

---

src/main.c

Changing value of Zoom length to see the clouds from the ground very close to me for Issue #54

Changing value of Zoom length to see the clouds from the ground very close to me for Issue #54

---

src/main.c

As a developer, I want to add Doxygen comments to the changes made to complete Issue #54.

 As a developer, I want to add Doxygen comments to the changes made to complete Issue #54.

---

src/main.c

As per review , Adding the link to the corresponding issue.

As per review , Adding the link to the corresponding issue

---

src/main.c

As part of user story #31, I want to add Doxygen comments to functions in the code so that the purpose of those functions is clearer.

As part of user story #31, I want to add Doxygen comments to functions in the code so that the purpose of those functions is clearer.

---

src/main.c

Adding Doxygen comments to functions in the code so that the purpose of those functions is clearer

Adding Doxygen comments to functions in the code so that the purpose of those functions is clearer

---

README.md
src/main.c

Issues #65 and #66

---

src/config.h
src/main.c

As a Developer, I want to terminate the complete session of the game by using the key button 'M' so that it closes the game all at once. #71

As a Developer, I want to terminate the complete session of the game by using the key button 'M' so that it closes the game all at once. #71

---

README.md

As part of user story #71 updating the README.md file

As part of user story #71 updating the README.md file

---

src/main.c

As per the reviewer's suggestion updated the code in main.c fie for user story #71

As per the reviewer's suggestion updated the code in main.c fie for user story #71

---

src/main.c

#69 and #65
If anyone knows what the max x, y, z coordinates are, please let me know so I can add limits to the teleport command.

Issues #69 and #65

---

src/main.c

This is primarily a test for forming a pull request. No coding is within the command calls...yet

Adding Command Spots for setting the time of day to dawn or dusk

---

src/main.c

Moved dawn and dusk commands (Issue 17) above if(foward) in main.c

---

src/main.c

programming by contract merges and doxygen

Jeb helped user story #1

---

CMakeLists.txt

Adds GoogleTest to the repository so we can implement better testing in response to issue https://github.com/WSU-CEG-6110-4410/ADAD-Craft/issues/92

Google test

---

src/main.c

Updating the Doxygen comments for issue #54 and #61

Updating the Doxygen comments for issue #54 and #61

---

CMakeLists.txt

Revert "Google test"

---

src/main.c

Updating the Doxygen Comments as well as Programming by Contract for user story #71

Updating the Doxygen Comments as well as Programming by Contract for user story #71

---

BACKLOG.md

Added 5 more issues to the backlog that had previously been discussed on discord and during team meetings.

Added 5 issues discussed on discord to the official BACKLOG.md file

---

src/main.c
src/unity.c
src/unity.h
src/unity_internals.h

Addresses https://github.com/WSU-CEG-6110-4410/ADAD-Craft/issues/122

Unit testing implementation and proof of concept

---

src/main.c

Contributes to https://github.com/WSU-CEG-6110-4410/ADAD-Craft/issues/125

Added unit test for collide_no_clip() function

---

src/main.c

Contributes to https://github.com/WSU-CEG-6110-4410/ADAD-Craft/issues/125

Fixed failure to launch, added test for chunked() function.

---

src/main.c

Contributes to https://github.com/WSU-CEG-6110-4410/ADAD-Craft/issues/125

Added unit test for highest_block() function.

---

BACKLOG.md

Added issue #122 and issue #19 to the backlog.

Back log updated

---

src/main.c

Issue #151

---

src/main.c

Issue #153

---

src/main.c

#155
The second commit should say #155, not #151.

Issue #155
